# Generated by Django 3.2.5 on 2022-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continents', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=50)),
                ('sales', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_priority', models.CharField(max_length=10)),
            ],
        ),
    ]
